services:
  irc:
    image: inspircd/inspircd-docker
    ports:
      - 6667:6667
  kafka:
    image: apache/kafka-native:4.1.1-rc2
    ports:
      - 9092:9092
  postgresql:
    image: postgres
    environment:
      - POSTGRES_DB=deploy42
      - POSTGRES_USER=deploy42
      - POSTGRES_PASSWORD=deploy42
    ports:
      - 5432:5432