[package]
name = "marv_api"
version = "0.1.0"
edition = "2024"

[lib]
name = "marv_api"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1.89"
diesel-async = "0.7.4"
once_cell = "1.21.3"
regex = "1.12.2"
serde = "1.0.228"
serde_cbor = "0.11.2"
tokio = "1.48.0"
toml = "0.9.8"
